from .IfcObjectDefinition import IfcObjectDefinition
from .IfcObject import IfcObject
from .IfcElement import IfcElement
from .IfcSpatialElement import IfcSpatialElement
from .IfcSpatialStructureElement import IfcSpatialStructureElement
from .IfcProduct import IfcProduct
from .IfcProject import IfcProject
from .IfcSite import IfcSite
from .IfcBuilding import IfcBuilding