"""
B-Rep Round-Trip Test
=====================

Tests the full B-Rep pipeline:
  OCCBrep (STEP) -> IfcAdvancedBrep -> save IFC -> reload -> compare volume/area

Uses the 26 STEP files generated by scripts/8.1_brep_generate.py as input.
Each file is loaded as an OCCBrep, written to IFC via brep_to_IfcAdvancedBrep
(use_occ=True), then reloaded and compared geometrically.

Since there is no parametric reader for IfcAdvancedBrep, the read-back uses
ifcopenshell's geometry evaluator (visual_geometry) which returns an OCCBrep
when use_occ=True.  Geometric accuracy is verified by comparing volume and
surface area between the original and round-tripped geometry.

Known evaluator limitations (not converter bugs):
  - Periodic surfaces (sphere, torus): ifcopenshell may fail to evaluate or
    produce reversed solid orientation, giving zero/wrong volume.
  - Boolean-cut voids (hollow_box, box_with_hole): the converter flattens
    IfcAdvancedBrepWithVoids into IfcAdvancedBrep (single IfcClosedShell) for
    viewer compatibility, so the evaluator sees all faces as one shell without
    knowing which are voids.
  - NURBS fallback surfaces (cone, cone_truncated): conical surfaces are
    converted to NURBS (no IfcConicalSurface in IFC4), adding approximation.
  - Complex topology (capsule=boolean fuse, nurbs_pillow=extruded NURBS,
    pipe_sweep=swept circle): evaluation may fail or produce different topology.

Prerequisites:
  Run scripts/8.1_brep_generate.py first to generate STEP files in
  temp/brep_conversion_tests/

Run with:
  conda run -n compas-ifc python thesis/roundtrip_brep.py
"""

import os
import sys

import ifcopenshell
import ifcopenshell.validate
from compas_occ.brep import OCCBrep

from compas_ifc.bim import BuildingInformationModel

# ==================================================================
# Test infrastructure
# ==================================================================

pass_count = 0
fail_count = 0
results = []


def check(label, condition, detail=""):
    global pass_count, fail_count
    status = "PASS" if condition else "FAIL"
    if condition:
        pass_count += 1
    else:
        fail_count += 1
    results.append((status, label, detail))
    return condition


# ==================================================================
# Paths
# ==================================================================

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STEP_DIR = os.path.join(REPO_ROOT, "temp", "brep_conversion_tests")
OUT_DIR = os.path.join(REPO_ROOT, "temp")
IFC_PATH = os.path.join(OUT_DIR, "thesis_roundtrip_brep.ifc")

# All 26 test shapes (matching scripts/8.1_brep_generate.py)
TEST_SHAPES = [
    # Surface types
    "plane_box",
    "cube",
    "cylinder",
    "sphere",
    "hemisphere",
    "torus",
    "torus_partial",
    "cone",
    "cone_truncated",
    "wedge",
    # Edge types
    "ellipsoid",
    "nurbs_pillow",
    # Mixed surfaces
    "box_filleted",
    "capsule",
    # Topology
    "hollow_box",
    "box_with_hole",
    "compound_two_boxes",
    "compound_box_cylinder",
    # Edge cases
    "tiny_box",
    "large_box",
    "thin_plate",
    "box_chamfered",
    "revolved_l_profile",
    "extruded_arc",
    "pipe_sweep",
    "thick_shell",
]

# ------------------------------------------------------------------
# Shape categories for tolerance and evaluation expectations
# ------------------------------------------------------------------

# Shapes where the round-trip volume/area should match closely (1% vol, 2% area)
# These use only planar, cylindrical, or simple surface types that ifcopenshell
# evaluates reliably.
STRICT_SHAPES = {
    "plane_box", "cube", "wedge", "tiny_box", "large_box", "thin_plate",
    "box_chamfered", "compound_two_boxes",
    "cylinder", "extruded_arc", "compound_box_cylinder",
    "box_filleted", "thick_shell",
}

# Shapes where NURBS approximation adds error (use 15% tolerance)
NURBS_SHAPES = {"cone", "cone_truncated"}

# Shapes with known ifcopenshell evaluator issues:
# - Periodic surfaces (sphere, torus): may fail to evaluate or give wrong orientation
# - Boolean-cut voids: converter flattens voids into single shell for viewer compat
# - Complex topology: boolean fuse, extruded NURBS, swept profiles
# These are checked as INFO (reported but not counted as failures).
KNOWN_ISSUES = {
    "sphere",             # periodic surface: evaluator may return None or wrong volume
    "hemisphere",         # partial sphere: evaluator may give wrong orientation
    "torus",              # doubly periodic: evaluator may return None
    "torus_partial",      # partial torus with caps: partial evaluation
    "ellipsoid",          # non-uniform scaled sphere -> NURBS: evaluator may fail
    "hollow_box",         # void flattened into single shell (no IfcAdvancedBrepWithVoids)
    "box_with_hole",      # void flattened into single shell
    "capsule",            # boolean fuse: complex topology after sew()
    "nurbs_pillow",       # extruded NURBS: complex evaluation
    "revolved_l_profile", # surface of revolution -> NURBS: complex evaluation
    "pipe_sweep",         # swept circle along arc: complex evaluation
}

# Expected IFC surface types per shape (spot-checks, not exhaustive)
EXPECTED_SURFACES = {
    "plane_box": ["IfcPlane"],
    "cube": ["IfcPlane"],
    "cylinder": ["IfcPlane", "IfcCylindricalSurface"],
    "sphere": ["IfcSphericalSurface"],
    "hemisphere": ["IfcSphericalSurface", "IfcPlane"],
    "torus": ["IfcToroidalSurface"],
    "cone": ["IfcRationalBSplineSurfaceWithKnots"],
    "extruded_arc": ["IfcCylindricalSurface"],
    "wedge": ["IfcPlane"],
}

# Tolerances
VOL_TOL_STRICT = 0.01   # 1% for well-behaved shapes
VOL_TOL_NURBS = 0.15    # 15% for NURBS-approximated shapes
SA_TOL_STRICT = 0.02    # 2% for surface area (tessellation differences)
SA_TOL_NURBS = 0.15     # 15% for NURBS shapes


# ==================================================================
# Check prerequisites
# ==================================================================

if not os.path.isdir(STEP_DIR):
    print(f"ERROR: STEP directory not found: {STEP_DIR}")
    print("       Run 'python scripts/8.1_brep_generate.py' first.")
    sys.exit(1)

available = [s for s in TEST_SHAPES if os.path.exists(os.path.join(STEP_DIR, f"{s}.stp"))]
missing = [s for s in TEST_SHAPES if s not in available]

if not available:
    print("ERROR: No STEP files found. Run 'python scripts/8.1_brep_generate.py' first.")
    sys.exit(1)

if missing:
    print(f"WARNING: {len(missing)} STEP files missing (will skip): {', '.join(missing)}")

print("=" * 70)
print("B-REP ROUND-TRIP TEST")
print("=" * 70)
print(f"\n  STEP directory: {STEP_DIR}")
print(f"  Shapes found:  {len(available)}/{len(TEST_SHAPES)}")
print(f"  Strict check:  {len(STRICT_SHAPES)} shapes (vol <1%, area <2%)")
print(f"  NURBS check:   {len(NURBS_SHAPES)} shapes (vol <15%)")
print(f"  Known issues:  {len(KNOWN_ISSUES)} shapes (INFO only)")
print()


# ==================================================================
# PART 1: WRITE — Load STEP files, create IFC with AdvancedBrep
# ==================================================================

print("=" * 70)
print("PART 1: WRITE (STEP -> OCCBrep -> IfcAdvancedBrep -> IFC)")
print("=" * 70)
print()

# Load all STEP files and record original properties
originals = {}  # name -> {"brep": OCCBrep, "volume": float, "area": float}
load_errors = []

for shape_name in available:
    step_path = os.path.join(STEP_DIR, f"{shape_name}.stp")
    try:
        brep = OCCBrep.from_step(step_path)
        vol = brep.volume
        area = brep.area
        originals[shape_name] = {"brep": brep, "volume": vol, "area": area}
        print(f"  Loaded {shape_name:<25s}  vol={vol:.6f}  area={area:.6f}")
    except Exception as e:
        load_errors.append((shape_name, str(e)))
        print(f"  FAILED {shape_name:<25s}  {e}")

print()
check("STEP load: all shapes loaded", len(load_errors) == 0,
      f"{len(load_errors)} errors: {', '.join(n for n, _ in load_errors)}" if load_errors else "")
print(f"  Loaded: {len(originals)}/{len(available)}  (errors: {len(load_errors)})")
print()

# Create IFC model with use_occ=True
print("  Creating IFC model with use_occ=True...")
model = BuildingInformationModel.template(schema="IFC4", unit="m", use_occ=True)
storey = model.storeys[0]

write_errors = []
for shape_name, data in originals.items():
    try:
        model.create_element(
            name=shape_name,
            geometry=data["brep"],
            parent=storey,
        )
    except Exception as e:
        write_errors.append((shape_name, str(e)))
        print(f"  WRITE FAILED: {shape_name}: {e}")

check("Write: all shapes written to IFC", len(write_errors) == 0,
      f"{len(write_errors)} errors" if write_errors else "")

# Save
os.makedirs(OUT_DIR, exist_ok=True)
model.save(IFC_PATH)
print(f"  Saved: {IFC_PATH}")
print(f"  Written: {len(originals) - len(write_errors)}/{len(originals)}")
print()

# ==================================================================
# Schema validation on the saved file
# ==================================================================

print("  Schema validation...")
validation_issues = []


class ValidationCollector:
    def warning(self, msg, *a, **kw):
        validation_issues.append(("WARN", str(msg)))

    def error(self, msg, *a, **kw):
        validation_issues.append(("ERR", str(msg)))


try:
    ifcopenshell.validate.validate(model.file._file, ValidationCollector())
except Exception as e:
    validation_issues.append(("ERR", f"validate() exception: {e}"))

schema_errors = [msg for level, msg in validation_issues if level == "ERR"]
schema_warnings = [msg for level, msg in validation_issues if level == "WARN"]

check("Schema: no validation errors", len(schema_errors) == 0,
      f"{len(schema_errors)} errors" if schema_errors else "")

if schema_errors:
    for msg in schema_errors[:5]:
        print(f"    ERR: {msg}")
    if len(schema_errors) > 5:
        print(f"    ... and {len(schema_errors) - 5} more")
if schema_warnings:
    print(f"    ({len(schema_warnings)} warnings)")

print()

# ==================================================================
# Check IFC entity types present
# ==================================================================

print("  Entity type checks...")
entity_types = {e.is_a() for e in model.file._file}

check("Entities: IfcAdvancedBrep present", "IfcAdvancedBrep" in entity_types, "")

for shape_name, expected_surfs in EXPECTED_SURFACES.items():
    if shape_name not in originals:
        continue
    for surf_type in expected_surfs:
        check(f"Surface: {shape_name} has {surf_type}", surf_type in entity_types, "")

print()


# ==================================================================
# PART 2: READ & COMPARE
# ==================================================================

print("=" * 70)
print("PART 2: READ & COMPARE (reload IFC -> compare volume/area)")
print("=" * 70)
print()

print("  Reloading IFC with use_occ=True...")
model2 = BuildingInformationModel(IFC_PATH, use_occ=True)
print(f"  Elements: {len(model2.building_elements)}")
print()

# Build lookup by name
reloaded_elems = {}
for elem in model2.building_elements:
    name = elem.name or ""
    if name:
        reloaded_elems[name] = elem


def compare_value(shape_name, metric, orig_val, reload_val):
    """Compare a metric (volume or surface_area) with appropriate tolerance.

    Returns (status_str, passed_bool) where status_str is one of:
    PASS, FAIL, INFO (for known issues).
    """
    is_known = shape_name in KNOWN_ISSUES
    is_nurbs = shape_name in NURBS_SHAPES

    if reload_val is None:
        if is_known:
            results.append(("INFO", f"{shape_name} {metric}", "evaluator returned None (known issue)"))
            return "INFO", True
        check(f"{shape_name} {metric}", False, f"reload {metric} is None")
        return "FAIL", False

    if orig_val is not None and orig_val > 1e-12:
        diff_pct = abs(reload_val - orig_val) / orig_val

        if is_known:
            # Report but don't fail
            results.append(("INFO", f"{shape_name} {metric}", f"{orig_val:.6f} vs {reload_val:.6f} ({diff_pct * 100:.2f}%)"))
            return "INFO" if diff_pct > 0.01 else "PASS", True

        if is_nurbs:
            tol = VOL_TOL_NURBS if metric == "volume" else SA_TOL_NURBS
        else:
            tol = VOL_TOL_STRICT if metric == "volume" else SA_TOL_STRICT

        ok = diff_pct < tol
        check(f"{shape_name} {metric}", ok, f"{orig_val:.6f} vs {reload_val:.6f} ({diff_pct * 100:.2f}%)")
        return "PASS" if ok else "FAIL", ok
    else:
        # Original volume ~ 0 (e.g. pipe_sweep which is a shell, tiny_box)
        if is_known:
            results.append(("INFO", f"{shape_name} {metric}", f"orig={orig_val:.6f} reload={reload_val:.6f}"))
            return "INFO", True
        ok = abs(reload_val) < 1e-6 if orig_val < 1e-12 else True
        check(f"{shape_name} {metric} (~0)", ok, f"{orig_val:.6f} vs {reload_val:.6f}")
        return "PASS" if ok else "FAIL", ok


# ------------------------------------------------------------------
# Volume comparison
# ------------------------------------------------------------------

print("  VOLUME COMPARISON:")
print("  " + "-" * 68)
print(f"  {'Name':<25s} {'Original':>12s} {'Reloaded':>12s} {'Diff%':>8s} {'Status'}")
print("  " + "-" * 68)

vol_pass = 0
vol_fail = 0
vol_info = 0

for shape_name in sorted(originals.keys()):
    orig_vol = originals[shape_name]["volume"]
    elem = reloaded_elems.get(shape_name)

    if elem is None:
        check(f"{shape_name} found after reload", False, "missing")
        vol_fail += 1
        print(f"  {shape_name:<25s} {'MISSING':>12s} {'':>12s} {'':>8s} FAIL")
        continue

    reload_vol = elem.volume
    status, ok = compare_value(shape_name, "volume", orig_vol, reload_vol)

    if status == "INFO":
        vol_info += 1
    elif ok:
        vol_pass += 1
    else:
        vol_fail += 1

    # Format output
    reload_str = f"{reload_vol:>12.6f}" if reload_vol is not None else f"{'None':>12s}"
    if reload_vol is not None and orig_vol > 1e-12:
        diff_str = f"{abs(reload_vol - orig_vol) / orig_vol * 100:>7.2f}%"
    elif reload_vol is not None:
        diff_str = f"{'~0':>8s}"
    else:
        diff_str = f"{'':>8s}"
    print(f"  {shape_name:<25s} {orig_vol:>12.6f} {reload_str} {diff_str} {status}")

print("  " + "-" * 68)
print(f"  Volume: {vol_pass} pass, {vol_fail} fail, {vol_info} info (known issues)")
print()

# ------------------------------------------------------------------
# Surface area comparison
# ------------------------------------------------------------------

print("  SURFACE AREA COMPARISON:")
print("  " + "-" * 68)
print(f"  {'Name':<25s} {'Original':>12s} {'Reloaded':>12s} {'Diff%':>8s} {'Status'}")
print("  " + "-" * 68)

sa_pass = 0
sa_fail = 0
sa_info = 0

for shape_name in sorted(originals.keys()):
    orig_area = originals[shape_name]["area"]
    elem = reloaded_elems.get(shape_name)

    if elem is None:
        continue  # already reported as missing

    reload_sa = elem.surface_area
    status, ok = compare_value(shape_name, "surface_area", orig_area, reload_sa)

    if status == "INFO":
        sa_info += 1
    elif ok:
        sa_pass += 1
    else:
        sa_fail += 1

    reload_str = f"{reload_sa:>12.6f}" if reload_sa is not None else f"{'None':>12s}"
    if reload_sa is not None and orig_area > 1e-12:
        diff_str = f"{abs(reload_sa - orig_area) / orig_area * 100:>7.2f}%"
    elif reload_sa is not None:
        diff_str = f"{'~0':>8s}"
    else:
        diff_str = f"{'':>8s}"
    print(f"  {shape_name:<25s} {orig_area:>12.6f} {reload_str} {diff_str} {status}")

print("  " + "-" * 68)
print(f"  Surface area: {sa_pass} pass, {sa_fail} fail, {sa_info} info (known issues)")
print()


# ==================================================================
# SUMMARY
# ==================================================================

print("=" * 70)
print("SUMMARY")
print("=" * 70)
print()

# Show failures
failures = [(s, l, d) for s, l, d in results if s == "FAIL"]
infos = [(s, l, d) for s, l, d in results if s == "INFO"]

if failures:
    print("  FAILURES:")
    for status, label, detail in failures:
        print(f"    {status}  {label}: {detail}")
    print()

if infos:
    print(f"  KNOWN ISSUES ({len(infos)} items, not counted as failures):")
    for status, label, detail in infos:
        print(f"    {status}  {label}: {detail}")
    print()

print(f"  {pass_count} PASS / {fail_count} FAIL  (of {pass_count + fail_count} checks)")
print(f"  ({len(infos)} additional INFO items for known evaluator limitations)")
print()

if fail_count == 0:
    print("SUCCESS: All B-Rep round-trip tests passed.")
else:
    print("WARNING: Some tests failed.")
    sys.exit(1)
