name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10', '3.11']

    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
          invoke_test: true
