"""Mixin providing element creation convenience methods for BuildingInformationModel."""

from __future__ import annotations

from typing import TYPE_CHECKING
from typing import Literal
from typing import overload

from compas.geometry import Transformation

from compas_ifc.element import GenericElement

if TYPE_CHECKING:
    # See bim.py for rationale; wildcard import keeps the @overload chain
    # below readable without listing every IFC product subclass by name.
    from compas_ifc.entities.generated.IFC4 import *  # noqa: F401, F403


class ElementFactoryMixin:
    """Mixin that adds element creation shortcuts to a Model subclass.

    Expects the host class to provide:
    - ``self.add_element(element, parent=...)`` — from compas_model.Model
    - ``self._file`` — :class:`IFCFile`
    - ``self.unit`` (settable)
    - ``self.name`` (settable)
    """

    # region overloads:create_element
    @overload
    def create_element(self, ifc_type: Literal["IfcActuator"]) -> GenericElement[IfcActuator]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcAirTerminal"]) -> GenericElement[IfcAirTerminal]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcAirTerminalBox"]) -> GenericElement[IfcAirTerminalBox]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcAirToAirHeatRecovery"]) -> GenericElement[IfcAirToAirHeatRecovery]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcAlarm"]) -> GenericElement[IfcAlarm]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcAnnotation"]) -> GenericElement[IfcAnnotation]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcAudioVisualAppliance"]) -> GenericElement[IfcAudioVisualAppliance]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBeam"]) -> GenericElement[IfcBeam]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBeamStandardCase"]) -> GenericElement[IfcBeamStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBoiler"]) -> GenericElement[IfcBoiler]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBuilding"]) -> GenericElement[IfcBuilding]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBuildingElement"]) -> GenericElement[IfcBuildingElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBuildingElementPart"]) -> GenericElement[IfcBuildingElementPart]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBuildingElementProxy"]) -> GenericElement[IfcBuildingElementProxy]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBuildingStorey"]) -> GenericElement[IfcBuildingStorey]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcBurner"]) -> GenericElement[IfcBurner]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCableCarrierFitting"]) -> GenericElement[IfcCableCarrierFitting]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCableCarrierSegment"]) -> GenericElement[IfcCableCarrierSegment]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCableFitting"]) -> GenericElement[IfcCableFitting]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCableSegment"]) -> GenericElement[IfcCableSegment]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcChiller"]) -> GenericElement[IfcChiller]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcChimney"]) -> GenericElement[IfcChimney]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCivilElement"]) -> GenericElement[IfcCivilElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCoil"]) -> GenericElement[IfcCoil]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcColumn"]) -> GenericElement[IfcColumn]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcColumnStandardCase"]) -> GenericElement[IfcColumnStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCommunicationsAppliance"]) -> GenericElement[IfcCommunicationsAppliance]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCompressor"]) -> GenericElement[IfcCompressor]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCondenser"]) -> GenericElement[IfcCondenser]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcController"]) -> GenericElement[IfcController]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCooledBeam"]) -> GenericElement[IfcCooledBeam]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCoolingTower"]) -> GenericElement[IfcCoolingTower]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCovering"]) -> GenericElement[IfcCovering]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcCurtainWall"]) -> GenericElement[IfcCurtainWall]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDamper"]) -> GenericElement[IfcDamper]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDiscreteAccessory"]) -> GenericElement[IfcDiscreteAccessory]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDistributionChamberElement"]) -> GenericElement[IfcDistributionChamberElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDistributionControlElement"]) -> GenericElement[IfcDistributionControlElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDistributionElement"]) -> GenericElement[IfcDistributionElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDistributionFlowElement"]) -> GenericElement[IfcDistributionFlowElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDistributionPort"]) -> GenericElement[IfcDistributionPort]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDoor"]) -> GenericElement[IfcDoor]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDoorStandardCase"]) -> GenericElement[IfcDoorStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDuctFitting"]) -> GenericElement[IfcDuctFitting]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDuctSegment"]) -> GenericElement[IfcDuctSegment]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcDuctSilencer"]) -> GenericElement[IfcDuctSilencer]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElectricAppliance"]) -> GenericElement[IfcElectricAppliance]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElectricDistributionBoard"]) -> GenericElement[IfcElectricDistributionBoard]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElectricFlowStorageDevice"]) -> GenericElement[IfcElectricFlowStorageDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElectricGenerator"]) -> GenericElement[IfcElectricGenerator]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElectricMotor"]) -> GenericElement[IfcElectricMotor]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElectricTimeControl"]) -> GenericElement[IfcElectricTimeControl]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElement"]) -> GenericElement[IfcElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElementAssembly"]) -> GenericElement[IfcElementAssembly]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcElementComponent"]) -> GenericElement[IfcElementComponent]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcEnergyConversionDevice"]) -> GenericElement[IfcEnergyConversionDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcEngine"]) -> GenericElement[IfcEngine]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcEvaporativeCooler"]) -> GenericElement[IfcEvaporativeCooler]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcEvaporator"]) -> GenericElement[IfcEvaporator]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcExternalSpatialElement"]) -> GenericElement[IfcExternalSpatialElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcExternalSpatialStructureElement"]) -> GenericElement[IfcExternalSpatialStructureElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFan"]) -> GenericElement[IfcFan]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFastener"]) -> GenericElement[IfcFastener]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFeatureElement"]) -> GenericElement[IfcFeatureElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFeatureElementAddition"]) -> GenericElement[IfcFeatureElementAddition]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFeatureElementSubtraction"]) -> GenericElement[IfcFeatureElementSubtraction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFilter"]) -> GenericElement[IfcFilter]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFireSuppressionTerminal"]) -> GenericElement[IfcFireSuppressionTerminal]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowController"]) -> GenericElement[IfcFlowController]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowFitting"]) -> GenericElement[IfcFlowFitting]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowInstrument"]) -> GenericElement[IfcFlowInstrument]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowMeter"]) -> GenericElement[IfcFlowMeter]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowMovingDevice"]) -> GenericElement[IfcFlowMovingDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowSegment"]) -> GenericElement[IfcFlowSegment]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowStorageDevice"]) -> GenericElement[IfcFlowStorageDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowTerminal"]) -> GenericElement[IfcFlowTerminal]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFlowTreatmentDevice"]) -> GenericElement[IfcFlowTreatmentDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFooting"]) -> GenericElement[IfcFooting]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFurnishingElement"]) -> GenericElement[IfcFurnishingElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcFurniture"]) -> GenericElement[IfcFurniture]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcGeographicElement"]) -> GenericElement[IfcGeographicElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcGrid"]) -> GenericElement[IfcGrid]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcHeatExchanger"]) -> GenericElement[IfcHeatExchanger]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcHumidifier"]) -> GenericElement[IfcHumidifier]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcInterceptor"]) -> GenericElement[IfcInterceptor]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcJunctionBox"]) -> GenericElement[IfcJunctionBox]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcLamp"]) -> GenericElement[IfcLamp]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcLightFixture"]) -> GenericElement[IfcLightFixture]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcMechanicalFastener"]) -> GenericElement[IfcMechanicalFastener]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcMedicalDevice"]) -> GenericElement[IfcMedicalDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcMember"]) -> GenericElement[IfcMember]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcMemberStandardCase"]) -> GenericElement[IfcMemberStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcMotorConnection"]) -> GenericElement[IfcMotorConnection]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcOpeningElement"]) -> GenericElement[IfcOpeningElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcOpeningStandardCase"]) -> GenericElement[IfcOpeningStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcOutlet"]) -> GenericElement[IfcOutlet]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPile"]) -> GenericElement[IfcPile]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPipeFitting"]) -> GenericElement[IfcPipeFitting]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPipeSegment"]) -> GenericElement[IfcPipeSegment]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPlate"]) -> GenericElement[IfcPlate]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPlateStandardCase"]) -> GenericElement[IfcPlateStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPort"]) -> GenericElement[IfcPort]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcProduct"]) -> GenericElement[IfcProduct]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcProjectionElement"]) -> GenericElement[IfcProjectionElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcProtectiveDevice"]) -> GenericElement[IfcProtectiveDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcProtectiveDeviceTrippingUnit"]) -> GenericElement[IfcProtectiveDeviceTrippingUnit]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcProxy"]) -> GenericElement[IfcProxy]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcPump"]) -> GenericElement[IfcPump]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcRailing"]) -> GenericElement[IfcRailing]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcRamp"]) -> GenericElement[IfcRamp]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcRampFlight"]) -> GenericElement[IfcRampFlight]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcReinforcingBar"]) -> GenericElement[IfcReinforcingBar]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcReinforcingElement"]) -> GenericElement[IfcReinforcingElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcReinforcingMesh"]) -> GenericElement[IfcReinforcingMesh]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcRoof"]) -> GenericElement[IfcRoof]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSanitaryTerminal"]) -> GenericElement[IfcSanitaryTerminal]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSensor"]) -> GenericElement[IfcSensor]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcShadingDevice"]) -> GenericElement[IfcShadingDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSite"]) -> GenericElement[IfcSite]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSlab"]) -> GenericElement[IfcSlab]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSlabElementedCase"]) -> GenericElement[IfcSlabElementedCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSlabStandardCase"]) -> GenericElement[IfcSlabStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSolarDevice"]) -> GenericElement[IfcSolarDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSpace"]) -> GenericElement[IfcSpace]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSpaceHeater"]) -> GenericElement[IfcSpaceHeater]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSpatialElement"]) -> GenericElement[IfcSpatialElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSpatialStructureElement"]) -> GenericElement[IfcSpatialStructureElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSpatialZone"]) -> GenericElement[IfcSpatialZone]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStackTerminal"]) -> GenericElement[IfcStackTerminal]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStair"]) -> GenericElement[IfcStair]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStairFlight"]) -> GenericElement[IfcStairFlight]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralAction"]) -> GenericElement[IfcStructuralAction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralActivity"]) -> GenericElement[IfcStructuralActivity]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralConnection"]) -> GenericElement[IfcStructuralConnection]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralCurveAction"]) -> GenericElement[IfcStructuralCurveAction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralCurveConnection"]) -> GenericElement[IfcStructuralCurveConnection]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralCurveMember"]) -> GenericElement[IfcStructuralCurveMember]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralCurveMemberVarying"]) -> GenericElement[IfcStructuralCurveMemberVarying]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralCurveReaction"]) -> GenericElement[IfcStructuralCurveReaction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralItem"]) -> GenericElement[IfcStructuralItem]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralLinearAction"]) -> GenericElement[IfcStructuralLinearAction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralMember"]) -> GenericElement[IfcStructuralMember]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralPlanarAction"]) -> GenericElement[IfcStructuralPlanarAction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralPointAction"]) -> GenericElement[IfcStructuralPointAction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralPointConnection"]) -> GenericElement[IfcStructuralPointConnection]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralPointReaction"]) -> GenericElement[IfcStructuralPointReaction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralReaction"]) -> GenericElement[IfcStructuralReaction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralSurfaceAction"]) -> GenericElement[IfcStructuralSurfaceAction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralSurfaceConnection"]) -> GenericElement[IfcStructuralSurfaceConnection]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralSurfaceMember"]) -> GenericElement[IfcStructuralSurfaceMember]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralSurfaceMemberVarying"]) -> GenericElement[IfcStructuralSurfaceMemberVarying]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcStructuralSurfaceReaction"]) -> GenericElement[IfcStructuralSurfaceReaction]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSurfaceFeature"]) -> GenericElement[IfcSurfaceFeature]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSwitchingDevice"]) -> GenericElement[IfcSwitchingDevice]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcSystemFurnitureElement"]) -> GenericElement[IfcSystemFurnitureElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcTank"]) -> GenericElement[IfcTank]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcTendon"]) -> GenericElement[IfcTendon]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcTendonAnchor"]) -> GenericElement[IfcTendonAnchor]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcTransformer"]) -> GenericElement[IfcTransformer]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcTransportElement"]) -> GenericElement[IfcTransportElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcTubeBundle"]) -> GenericElement[IfcTubeBundle]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcUnitaryControlElement"]) -> GenericElement[IfcUnitaryControlElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcUnitaryEquipment"]) -> GenericElement[IfcUnitaryEquipment]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcValve"]) -> GenericElement[IfcValve]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcVibrationIsolator"]) -> GenericElement[IfcVibrationIsolator]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcVirtualElement"]) -> GenericElement[IfcVirtualElement]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcVoidingFeature"]) -> GenericElement[IfcVoidingFeature]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcWall"]) -> GenericElement[IfcWall]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcWallElementedCase"]) -> GenericElement[IfcWallElementedCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcWallStandardCase"]) -> GenericElement[IfcWallStandardCase]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcWasteTerminal"]) -> GenericElement[IfcWasteTerminal]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcWindow"]) -> GenericElement[IfcWindow]: ...
    @overload
    def create_element(self, ifc_type: Literal["IfcWindowStandardCase"]) -> GenericElement[IfcWindowStandardCase]: ...
    @overload
    def create_element(self, ifc_type: str) -> GenericElement: ...
    # endregion overloads:create_element
    def create_element(self, ifc_type="IfcBuildingElementProxy", parent=None, geometry=None, frame=None, transformation=None, properties=None, name=None):
        """Create a building element and add it to the model.

        The ``ifc_type`` argument accepts flexible input. If the value matches
        an IFC class (case-insensitive, with or without the ``Ifc`` prefix —
        ``"IfcWall"``, ``"Wall"``, ``"wall"`` are all equivalent), the element
        is created with that IFC class. If the value matches no known class,
        the element falls back to ``IfcBuildingElementProxy`` and the original
        string is stored as ``ObjectType`` so semantic identity is preserved.

        Parameters
        ----------
        ifc_type : str
            The IFC class name (e.g. ``"IfcWall"``, ``"Wall"``) or any custom
            string for non-standard products.
        parent : GenericElement, optional
            Parent in the spatial hierarchy.
        geometry : Brep | Mesh | Shape, optional
            Element geometry.
        frame : Frame, optional
            Placement frame (converted to Transformation).
        transformation : Transformation, optional
            Local transformation. Overrides frame if both provided.
        properties : dict, optional
            Property sets.
        name : str, optional
            Element name.

        Returns
        -------
        GenericElement

        """
        if transformation is None and frame is not None:
            transformation = Transformation.from_frame(frame)

        canonical, custom_object_type = self._normalise_ifc_type(ifc_type)

        element = GenericElement(
            ifc_type=canonical,
            geometry=geometry,
            transformation=transformation,
            name=name,
        )

        merged_properties = dict(properties) if properties else {}
        if custom_object_type is not None:
            merged_properties.setdefault("ObjectType", custom_object_type)
        if merged_properties:
            element._properties = merged_properties

        self.add_element(element, parent=parent)
        return element

    def _normalise_ifc_type(self, ifc_type):
        """Resolve a user-supplied type string against the active IFC schema.

        Returns a tuple ``(canonical, custom_object_type)``. ``canonical`` is
        the matched IFC class name (e.g. ``"IfcWall"``). ``custom_object_type``
        is ``None`` when the match was direct, or the original string when the
        value did not map to any IFC class — in which case ``canonical`` is
        ``"IfcBuildingElementProxy"`` and the original string is preserved as
        ``ObjectType`` on the resulting entity.
        """
        if not isinstance(ifc_type, str) or not ifc_type:
            return "IfcBuildingElementProxy", None

        classes = self._file.classes
        # 1. exact match
        if ifc_type in classes:
            return ifc_type, None
        # 2. case-insensitive match
        lower_to_canonical = {c.lower(): c for c in classes}
        if ifc_type.lower() in lower_to_canonical:
            return lower_to_canonical[ifc_type.lower()], None
        # 3. prefix-stripped variants ("Wall" -> "IfcWall")
        if not ifc_type.lower().startswith("ifc"):
            prefixed = "ifc" + ifc_type.lower()
            if prefixed in lower_to_canonical:
                return lower_to_canonical[prefixed], None
        # 4. unknown -> proxy with the user string preserved as ObjectType
        return "IfcBuildingElementProxy", ifc_type

    def create_wall(self, **kwargs) -> GenericElement[IfcWall]:
        """Create an IfcWall and add it to the model."""
        return self.create_element(ifc_type="IfcWall", **kwargs)

    def create_slab(self, **kwargs) -> GenericElement[IfcSlab]:
        """Create an IfcSlab and add it to the model."""
        return self.create_element(ifc_type="IfcSlab", **kwargs)

    def create_beam(self, **kwargs) -> GenericElement[IfcBeam]:
        """Create an IfcBeam and add it to the model."""
        return self.create_element(ifc_type="IfcBeam", **kwargs)

    def create_column(self, **kwargs) -> GenericElement[IfcColumn]:
        """Create an IfcColumn and add it to the model."""
        return self.create_element(ifc_type="IfcColumn", **kwargs)

    def create_window(self, **kwargs) -> GenericElement[IfcWindow]:
        """Create an IfcWindow and add it to the model."""
        return self.create_element(ifc_type="IfcWindow", **kwargs)

    def create_door(self, **kwargs) -> GenericElement[IfcDoor]:
        """Create an IfcDoor and add it to the model."""
        return self.create_element(ifc_type="IfcDoor", **kwargs)

    def create_roof(self, **kwargs) -> GenericElement[IfcRoof]:
        """Create an IfcRoof and add it to the model."""
        return self.create_element(ifc_type="IfcRoof", **kwargs)

    @classmethod
    def template(cls, schema="IFC4", building_count=1, storey_count=1, unit="mm", use_occ=False, name=None):
        """Create a template BIM model with default spatial hierarchy.

        Creates IfcProject → IfcSite → IfcBuilding(s) → IfcBuildingStorey(s).

        Parameters
        ----------
        schema : str
            IFC schema version. Default is "IFC4".
        building_count : int
            Number of buildings. Default is 1.
        storey_count : int
            Number of storeys per building. Default is 1.
        unit : str
            Length unit ("mm", "cm", or "m"). Default is "mm".
        use_occ : bool
            Use OpenCascade for geometry. Default is False.
        name : str, optional
            Model name.

        Returns
        -------
        BuildingInformationModel

        """
        model = cls(schema=schema, use_occ=use_occ, name=name or "Default Project")

        # Ensure default project exists in IFC file
        project = model._file.default_project
        model.name = project.Name or "Default Project"

        site = GenericElement(ifc_type="IfcSite", name="Default Site")
        model.add_element(site)

        for i in range(building_count):
            building = GenericElement(ifc_type="IfcBuilding", name=f"Default Building {i + 1}")
            model.add_element(building, parent=site)

            for j in range(storey_count):
                storey = GenericElement(ifc_type="IfcBuildingStorey", name=f"Default Storey {j + 1}")
                model.add_element(storey, parent=building)

        model.unit = unit
        return model
